version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './src:/var/www/localhost'
    links:
      - php
  php:
    build: 'php'
    volumes:
      - './src:/var/www/localhost'
